name: 'Log Pattern Checker'
description: 'Check log files for specific patterns'

# Define your inputs here.
inputs:
  file-path:
    description: 'Path to the log file to check'
    required: true
  show-lines:
    description: 'Control how many lines to show (all, none, default)'
    required: false
    default: 'default'

runs:
  using: node20
  main: dist/index.js
