name: 'Log Pattern Checker'
description: 'Check log files for specific patterns'

inputs:
  filePath:
    description: 'Path to the log file to check'
    required: true
  showLines:
    description: 'Control how many lines to show (all, none, default)'
    required: false
    default: 'default'
  logType:
    description: 'Type of log to check (e.g., node, python, java)'
    required: false
    default: 'unity'
  matchOutputMaxChars:
    description: 'Max size of matchOutput output variable'
    required: false
    default: '500'
outputs:
  matchOutput:
    description: 'Print matched output also to variable'

runs:
  using: node20
  main: dist/index.js
